// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoUsiCP4RmPnMGgs3KxsQPAquEjUQs1CQ',
    appId: '1:646088207942:web:73bc8f9e4df7a21c266447',
    messagingSenderId: '646088207942',
    projectId: 'fodei-4776d',
    authDomain: 'fodei-4776d.firebaseapp.com',
    storageBucket: 'fodei-4776d.appspot.com',
    measurementId: 'G-VWKCXL67B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4PbAW_7Mc_XXl81ynsA6IZ1vq5yAKheU',
    appId: '1:646088207942:android:c494dfd9e93aa97f266447',
    messagingSenderId: '646088207942',
    projectId: 'fodei-4776d',
    storageBucket: 'fodei-4776d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQAHfHu21KORMSyqyLgXmaqzqb2w1E680',
    appId: '1:646088207942:ios:428c1be3eb80b77c266447',
    messagingSenderId: '646088207942',
    projectId: 'fodei-4776d',
    storageBucket: 'fodei-4776d.appspot.com',
    iosClientId: '646088207942-p8uu0t6nrobc3kq4217p23s7snb5e28n.apps.googleusercontent.com',
    iosBundleId: 'com.example.fodei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQAHfHu21KORMSyqyLgXmaqzqb2w1E680',
    appId: '1:646088207942:ios:b3dee79273dde4a8266447',
    messagingSenderId: '646088207942',
    projectId: 'fodei-4776d',
    storageBucket: 'fodei-4776d.appspot.com',
    iosClientId: '646088207942-22th6e3nfvdf8htumm8dd0qon2prpkr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fodei.RunnerTests',
  );
}
